### ISSUE TITLE
Unhandled Exception attempting to pull license for package EPPlus, version 4.5.3.3

### ISSUE THREAD

**Issue by s-michael-telford** [Sigvaard/dotnet-license#10]
I received an unhandled exception running the tool against a .Net6 Console application that includes EPPlus, version 4.5.5.3.  

From the .csproj
\<PackageReference Include="EPPlus" Version="4.5.3.3" /\>

I've attached the full output from the tool run, only editing out my path, but the top of the exception stack is:
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DotnetThirdPartyNotices.GithubService.GetLicenseContentFromRepositoryPath(String repositoryPath) in /home/runner/work/DotnetThirdPartyNotices/DotnetThirdPartyNotices/src/DotnetThirdPartyNotices/GithubService.cs:line 35

This package is interesting as it's marked deprecated by the developer as he changed the license in subsequent versions, which may explain the different behavior.

**Comment by s-michael-telford** [comment]
[output.txt](https://github.com/bugproof/DotnetThirdPartyNotices/files/11236658/output.txt)

**Comment by bugproof** [comment]
It needs a custom license uri resolver implementation similar to https://github.com/bugproof/DotnetThirdPartyNotices/blob/master/src/DotnetThirdPartyNotices/LicenseResolvers/OpenSourceOrgLicenseResolver.cs

I currently don't have time to work on this tool (not useful for me atm). If this is still important for you, you're welcome to fund this issue via polar. Otherwise, if you have time to add this yourself you're welcome to open a PR 👍

**Comment by danielklecha** [comment]
EPPlus 4.5.5.3 contains lgpl-3.0.txt in package folder.
Tool can read this information from nuspec file - I added support for this in #12.
You get 404 from github because project in github don't have a license - I also fixed this in PR.

**Comment by danielklecha** [comment]
PR #12 was merged. It should work now.
